matrix:
  type: spider
  axis_layout:
    label_font_size: 8.0
    value_font_size: 5.0
    width: 2.0
    color: "006600"
    max_span: 200.0
    scale_length: 4.0
    scale_width: 0.5
  legend:
    font_size: 24.0
  axis:
    -
      key: aut
      name: "Autonomie"
    -
      key: klim
      name: "Bedrijfsklimaat"
    -
      key: bel
      name: "Beleid"
    -
      key: besl
      name: "Besluitvorming"
    -
      key: des
      name: "Deskundigheid"
    -
      key: hou
      name: "Houding"
    -
      key: inv
      name: "Invloed"
      min: -15
      max: 15
      step: 5
    -
      key: org
      name: "Organisatie"
    -
      key: sam
      name: "Samenwerking"
  data:
    -
      name: "Iedereen"
      color: "FF0000"
      values:
        aut: 0.5
        klim: 0.3
        bel: 0.1
        besl: 0.7
        des: 0.5
        hou: 0.9
        inv: 5
        org: 0.2
        sam: 0.4
    -
      name: "Bouw"
      color: "0000FF"
      values:
        aut: 0.65
        klim: 0.7
        bel: 0.2
        besl: 0.4
        des: 0.1
        hou: 0.6
        inv: -6
        org: 0.3
        sam: 0.1
trilinear:
  type: trilinear
  layout:
    size: 200
    label-font-size: 20
    scale:
      font-size: 15
      steps: 10
      color: "0000FF"
      width: 1.0    
    border:
      color: "00FF00"
      width: 3.0

  left-axis:
    name: "Sociaal"
    alias: social
  right-axis:
    name: "Economie"
    alias: economy
  bottom-axis:
    name: "Ecologie"
    alias: ecology
  data:
    -
      social: 0.3333
      economy: 0.3333
      ecology: 0.3334
    -
      social: 0.1
      economy: 0.6
      ecology: 0.3
      

  